image: "/home/darpan/fdc_copy_local/selected-for-prints/IIITH/20250329_124353.jpg"
img_dir: "path/to/image_directory"
colormap_csv: "/home/darpan/pipeline_code_darpan_local_copy/pipeline_code/config/colormap_new.csv"
prototypes: "/home/darpan/pipeline_code_darpan_local_copy/embeddings_PE-Core-L14-336_selcted_30_patches"
proto_ckpt: null
k: 5
sim_thr: 0.6
device: "cuda"
sam_cfg: "configs/sam2.1/sam2.1_hiera_l.yaml"
sam_ckpt: "/home/darpan/pipeline_code_darpan_local_copy/sam2.1_hiera_large.pt"
gdino_cfg: "grounding_dino/groundingdino/config/GroundingDINO_SwinB_cfg.py"
gdino_ckpt: "/home/darpan/pipeline_code_darpan_local_copy/groundingdino_swinb_cogcoor.pth"
output_dir: "/home/darpan/pipeline_code_darpan_local_copy/v12/output_dir"
num_patches: 20
patch_size: 64
menu_json: "/home/darpan/pipeline_code_darpan_local_copy/pipeline_code/config/menu.json"
date: "20250329"
upload_dir: "/home/darpan/pipeline_code_darpan_local_copy/v12/upload_dir"
config: "/home/darpan/pipeline_code_darpan_local_copy/pipeline_code/config/experiment_core_patches.yaml"
